import {
  Apples,
  CoffeeCapsule,
  Apple,
  Asparagus,
  Apricot,
  Avocado,
  Bacon,
  Baguette,
  Bake,
  Banana,
  Barbeque,
  Basil,
  Beef,
  BerryJam,
  BirthdayCake,
  Biscuits,
  Blueberry,
  BoxOfCereal,
  BreadAndRollingPin,
  BreadAndRye,
  BreadLoaf,
  Brezel,
  Burrito,
  Cake,
  Calories,
  Carbohydrates,
  Cauliflower,
  Cherry,
  CherryCheesecake,
  ChiaSeeds,
  ChineseNoodle,
  ChocolateBar1,
  ChocolateBar2,
  ChocolateSpread,
  CinnamonSticks,
  CoconutMilk,
  CoffeeBeans,
  Cola1,
  Cola2,
  Crab,
  Croissant,
  CutePumpkin,
  CutsOfPork,
  Dairy,
  DiabeticFood,
  DimSum,
  Doughnut,
  DozenEggs,
  DragonFruit,
  Durian,
  EggBasket,
  EggCarton,
  EggStand,
  Eggplant,
  Eggs,
  FastFoodDriveThru,
  Fiber,
  Flour,
  FoodDonor,
  FrenchFries,
  FriedChicken,
  FruitBag,
  Fry,
  GrainsOfRice,
  HalalFood,
  Hamburger,
  Hamper,
  HealthyEating,
  HempMilk,
  Honey,
  HotDog,
  IceCreamSundae,
  IngredientsForCooking,
  InternationalFood,
  IranianKebab,
  Jam,
  Jamon,
  KawaiiBread,
  KawaiiBroccoli,
  KawaiiCoffee,
  KawaiiCroissant,
  KawaiiCupcake,
  KawaiiEgg,
  KawaiiFrenchFries,
  KawaiiIceCream,
  KawaiiJam,
  KawaiiMilk,
  KawaiiNoodle,
  KawaiiPizza,
  KawaiiShellfish,
  KawaiiSoda,
  KawaiiSteak,
  KawaiiTaco,
  Kebab,
  KfcChicken,
  Kiwi,
  Kohlrabi,
  Lasagna,
  Leek,
  Lime,
  LowCholesterolFood,
  Macaron,
  Mangosteen,
  Mayonnaise,
  Melon,
  MeltingIceCream,
  MerryPie,
  MilkCarton,
  MushboohFood,
  Mushroom,
  Nachos,
  NoCelery,
  NoCrustaceans,
  NoFish,
  NoGmo,
  NoMeat,
  NoNuts,
  NoPork,
  PapayaNoSesame,
  NoShellfish,
  NoSugar,
  NonLactoseFood,
  NonyaKueh,
  PeasOatMilk,
  PecanOlive,
  Paella,
  PaleoDiet,
  Pancake,
  Papaya,
  Peach,
  Peanut,
  Peanuts,
  Pear,
  Peas,
  Pecan,
  Picnic,
  Pineapple,
  Pizza,
  PizzaFiveEighths,
  PlasticFoodContainer,
  Plum,
  Pomegranate,
  Popcorn,
  Porridge,
  Pretzel,
  Quesadilla,
  Radish,
  Raspberry,
  Refreshments,
  Roast,
  RolledOats,
  RottenTomatoes,
  Salad1,
  Salad2,
  SalamiPizza,
  SalmonSushi,
  SaltShaker,
  Samosa,
  Sandwich,
  SandwichWithFriedEgg,
  Sauce,
  Seafood,
  Sesame,
  ShrimpAndLobster,
  SweetPotatoSliceOfWatermelon,
  Sodium,
  SoupPlate,
  Spaghetti,
  SpamCan,
  Spice,
  Steak,
  SugarCubes,
  SunnySideUpEggs,
  Sushi,
  SweetPotato,
  Taco,
  TakeAwayFood,
  Tangelo,
  Tapas,
  Thanksgiving,
  Tiffin,
  TinCan,
  Toast,
  VeganFood,
  VegetarianMark,
  Watermelon,
  WhippedCream,
  WholeMelon,
  WickerBasket,
  WorcestershireSauce,
  Wrap,
  CottonCandy,
  Cookie,
  Corn,
  Cerial,
} from "./icon";

export const Icons = {
  icon1: Apple,
  icon2: Apples,
  icon3: Apricot,
  icon4: Asparagus,
  icon5: Avocado,
  icon6: Bacon,
  icon7: Baguette,
  icon8: Bake,
  icon9: Banana,
  icon10: Barbeque,
  icon11: Basil,
  icon12: Beef,
  icon13: BerryJam,
  icon14: BirthdayCake,
  icon15: Biscuits,
  icon16: Blueberry,
  icon17: BoxOfCereal,
  icon18: BreadAndRollingPin,
  icon19: BreadAndRye,
  icon20: BreadLoaf,
  icon22: Brezel,
  icon23: Burrito,
  icon24: Cake,
  icon25: Calories,
  icon26: Carbohydrates,
  icon27: Cauliflower,
  icon28: Cerial,
  icon29: Cherry,
  icon30: CherryCheesecake,
  icon31: ChiaSeeds,
  icon32: ChineseNoodle,
  icon33: ChocolateBar1,
  icon34: ChocolateBar2,
  icon35: ChocolateSpread,
  icon36: CinnamonSticks,
  icon37: CoconutMilk,
  icon38: CoffeeBeans,
  icon39: CoffeeCapsule,
  icon40: Cola1,
  icon41: Cola2,
  icon42: Cookie,
  icon43: Corn,
  icon44: CottonCandy,
  icon45: Crab,
  icon46: Croissant,
  icon47: CutePumpkin,
  icon48: CutsOfPork,
  icon49: Dairy,
  icon50: DiabeticFood,
  icon51: DimSum,

  icon52: Doughnut,
  icon53: DozenEggs,
  icon54: DragonFruit,
  icon55: Durian,
  icon56: EggBasket,
  icon57: EggCarton,
  icon58: EggStand,
  icon59: Eggplant,
  icon60: Eggs,
  icon61: FastFoodDriveThru,
  icon62: Fiber,
  icon63: Flour,
  icon64: FoodDonor,
  icon65: FrenchFries,

  icon66: FriedChicken,
  icon67: FruitBag,
  icon68: Fry,
  icon69: GrainsOfRice,
  icon70: HalalFood,
  icon71: Hamburger,
  icon72: Hamper,
  icon73: HealthyEating,
  icon74: HempMilk,
  icon75: Honey,
  icon76: HotDog,
  icon77: IceCreamSundae,
  icon78: IngredientsForCooking,
  icon79: InternationalFood,
  icon80: IranianKebab,
  icon81: Jam,
  icon82: Jamon,
  icon83: KawaiiBread,
  icon84: KawaiiBroccoli,
  icon85: KawaiiCoffee,
  icon86: KawaiiCroissant,

  icon87: KawaiiCupcake,
  icon88: KawaiiEgg,
  icon89: KawaiiFrenchFries,
  icon90: KawaiiIceCream,

  icon91: KawaiiJam,
  icon92: KawaiiMilk,
  icon93: KawaiiNoodle,
  icon94: KawaiiPizza,
  icon95: KawaiiShellfish,
  icon96: KawaiiSoda,
  icon97: KawaiiSteak,
  icon98: KawaiiTaco,
  icon99: Kebab,

  icon100: KfcChicken,
  icon101: Kiwi,
  icon102: Kohlrabi,
  icon103: Lasagna,
  icon104: Leek,
  icon105: Lime,
  icon106: LowCholesterolFood,
  icon107: Macaron,
  icon108: Mangosteen,
  icon109: Mayonnaise,

  icon110: Melon,
  icon111: MeltingIceCream,
  icon112: MerryPie,
  icon113: MilkCarton,
  icon114: MushboohFood,
  icon115: Mushroom,
  icon116: Nachos,
  icon117: NoCelery,
  icon118: NoCrustaceans,
  icon119: NoFish,

  icon120: NoGmo,
  icon121: NoMeat,
  icon122: NoNuts,
  icon123: NoPork,
  icon124: PapayaNoSesame,
  icon125: NoShellfish,
  icon126: NoSugar,
  icon127: NonLactoseFood,
  icon128: NonyaKueh,
  icon129: PeasOatMilk,

  icon130: PecanOlive,
  icon131: Paella,
  icon132: PaleoDiet,
  icon133: Pancake,
  icon134: Papaya,
  icon135: Peach,
  icon136: Peanut,
  icon137: Peanuts,
  icon138: Pear,
  icon139: Peas,

  icon140: Pecan,
  icon141: Picnic,
  icon142: Pineapple,
  icon143: Pizza,
  icon144: PizzaFiveEighths,
  icon145: PlasticFoodContainer,
  icon146: Plum,
  icon147: Pomegranate,
  icon148: Popcorn,
  icon149: Porridge,

  icon150: Pretzel,
  icon151: Quesadilla,
  icon152: Radish,
  icon153: Raspberry,
  icon154: Refreshments,
  icon155: Roast,
  icon156: RolledOats,
  icon157: RottenTomatoes,
  icon158: Salad1,
  icon159: Salad2,

  icon160: SalamiPizza,
  icon161: SalmonSushi,
  icon162: SaltShaker,
  icon163: Samosa,
  icon164: Sandwich,
  icon165: SandwichWithFriedEgg,
  icon166: Sauce,
  icon167: Seafood,
  icon168: Sesame,
  icon169: ShrimpAndLobster,

  icon170: SweetPotatoSliceOfWatermelon,
  icon171: Sodium,
  icon172: SoupPlate,
  icon173: Spaghetti,
  icon174: SpamCan,
  icon175: Spice,
  icon176: Steak,
  icon177: SugarCubes,
  icon178: SunnySideUpEggs,
  icon179: Sushi,

  icon180: SweetPotato,
  icon181: Taco,
  icon182: TakeAwayFood,
  icon183: Tangelo,
  icon184: Tapas,
  icon185: Thanksgiving,
  icon186: Tiffin,
  icon187: TinCan,
  icon188: Toast,
  icon189: VeganFood,
  icon190: VegetarianMark,
  icon191: Watermelon,
  icon192: WhippedCream,
  icon193: WholeMelon,
  icon194: WickerBasket,
  icon195: WorcestershireSauce,
  icon196: Wrap,
};
